name: The Lighter Side of Arcangel
favicon: null
layout_spectrum: 0.07934
typography_spectrum: 0.26782
title: 'Coo, airy images from the arcangel collection'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f2f0'
    - '#020202'
    - '#a5a8b4'
    - '#3f4046'
    - '#447c8f'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
