name: The Lighter Side of Arcangel
favicon: null
layout_spectrum: 0.5410574828274548
typography_spectrum: 0.6255575343966484
title: 'Coo, airy images from the arcangel collection'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.0625
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
